export const GET_BASKET = "GET_BASKET"
export const ADD_TO_BASKET = "ADD_TO_BASKET"
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET"
export const SET_PRICE = "SET_PRICE"
export const SET_LOADING = "SET_LOADING"