export const GET_USERS = "GET_USERS"
export const GET_USER = "GET_USER"
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE"
export const SET_SIZE_PAGE = "SET_SIZE_PAGE"
export const SET_LOADING = "SET_LOADING"